---
# Playbook to setup OCP4 install host

- name: Deploy CLI utilities for deploying Red Hat OpenShift
  hosts: localhost
  become: True
  vars:

  tasks:

# Setup temp directory in current working directory

    - name: Get current_working_directory
      command: pwd
      register: current_working_directory

    - name: Generate temp directory in working directory
      file:
        path: "{{ current_working_directory.stdout }}/temp"
        state: directory
      register: temp_dir

# Openshift oc command

    - name: Download the latest oc command
      get_url: 
        url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-client-linux.tar.gz"
        dest: "{{ temp_dir.path }}/openshift-client-linux.tar.gz"
      tags:            
        - oc           
        - kubectl   

    - name: Install oc and kubectl into /usr/local/bin
      command: "{{ item }}"
      args:
        chdir: "{{ temp_dir.path }}"
      with_items:
        - "tar -xvf openshift-client-linux.tar.gz -C /usr/local/bin"
        - "rm -f {{ temp_dir.path }}/openshift-client-linux.tar.gz /usr/local/bin/README.md"
      tags:
        - oc
        - kubectl

    - name: Install oc and kubectl cli completion script              
      command: "{{ item }}"
      with_items:
        - "/usr/local/bin/oc completion bash > /etc/bash_completion.d/oc-completion"
        - "/usr/local/bin/kubectl completion bash > /etc/bash_completion.d/kubectl-completion"
      tags:
        - oc
        - kubectl
     
# Openshift Installer
    - name: Download the latest openshift-install
      get_url:
        url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-install-linux.tar.gz"
        dest: "{{ temp_dir.path }}/openshift-install-linux.tar.gz"
      tags:
        - openshift-install

    - name: Install openshift-install into /usr/local/bin
      command: "{{ item }}"
      args:
        chdir: "{{ temp_dir.path }}"
      with_items:
        - "tar -xvf openshift-install-linux.tar.gz -C /usr/local/bin"
        - "rm -f {{ temp_dir.path }}/openshift-install-linux.tar.gz /usr/local/bin/README.md"
      tags:
        - openshift-install

    - name: Install openshift-install completion script
      command: "/usr/local/bin/openshift-install completion bash > /etc/bash_completion.d/openshift-install-completion"
      tags: openshift-install

# Helm Tool
    - name: Download and install the latest Helm tool
      get_url:
        url: "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/helm/latest/helm-linux-amd64"
        dest: "/usr/local/bin/helm"
        mode: "0555"
      tags:
        - helm

    - name: Install Helm completion script
      command: "/usr/local/bin/helm completion bash > /etc/bash_completion.d/helm-completion"
      tags: helm

# Install completion scripts
    - name: Install completion scripts
      command: "{{ item }}"
      args:
        executable: /bin/bash
      with_items:
        - "/usr/local/bin/oc completion bash > /etc/bash_completion.d/oc-completion"

# Post 
  post_tasks:
    - name: Remove temp directory
      file:
         path: "{{  current_working_directory.stdout }}/temp"
         state: absent

